### ISSUE TITLE
Test - AppComponent Error about Router

### ISSUE THREAD

**Issue by EdwardBaek** [EdwardBaek/-DailyWordbookTOCFL#1]
# AppComponent Error about Router in Test

##  #1 Failed: Component HomeComponent is not part of any NgModule or the module has not been imported into your module.

```
Error: Component HomeComponent is not part of any NgModule or the module has not been imported into your module.
    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._createCompiledHostTemplate (http://localhost:9876/_karma_webpack_/webpack:/mnt/c/UbuntuOnWindow/Document/Projects/DailyWordbook-TOCFL/node_modules/@angular/compiler/esm5/compiler.js:34540:1)
    at http://localhost:9876/_karma_webpack_/webpack:/mnt/c/UbuntuOnWindow/Document/Projects/DailyWordbook-TOCFL/node_modules/@angular/compiler/esm5/compiler.js:34492:1
    at Array.forEach (<anonymous>)
    at http://localhost:9876/_karma_webpack_/webpack:/mnt/c/UbuntuOnWindow/Document/Projects/DailyWordbook-TOCFL/node_modules/@angular/compiler/esm5/compiler.js:34489:1
    at Array.forEach (<anonymous>)
    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._compileComponents (http://localhost:9876/_karma_webpack_/webpack:/mnt/c/UbuntuOnWindow/Document/Projects/DailyWordbook-TOCFL/node_modules/@angular/compiler/esm5/compiler.js:34478:1)
    at http://localhost:9876/_karma_webpack_/webpack:/mnt/c/UbuntuOnWindow/Document/Projects/DailyWordbook-TOCFL/node_modules/@angular/compiler/esm5/compiler.js:34384:1
    at Object.then (http://localhost:9876/_karma_webpack_/webpack:/mnt/c/UbuntuOnWindow/Document/Projects/DailyWordbook-TOCFL/node_modules/@angular/compiler/esm5/compiler.js:474:33)
    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._compileModuleAndAllComponents (http://localhost:9876/_karma_webpack_/webpack:/mnt/c/UbuntuOnWindow/Document/Projects/DailyWordbook-TOCFL/node_modules/@angular/compiler/esm5/compiler.js:34382:1)
    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler.compileModuleAndAllComponentsAsync (http://localhost:9876/_karma_webpack_/webpack:/mnt/c/UbuntuOnWindow/Document/Projects/DailyWordbook-TOCFL/node_modules/@angular/compiler/esm5/compiler.js:34281:1)
```

**Comment by EdwardBaek** [comment]
### Solution
Add required components to TestBed config setting.
```typescript
TestBed.configureTestingModule({
      declarations: [
        AppComponent,
        HomeComponent,
        QuizComponent,
        QuizSettingComponent,
        QuizScoreComponent,
        QuizQuestionComponent,
        WordListComponent,
        RecordListComponent,
        SettingComponent,
        NotFoundComponent
      ],
      imports: [
        AppRoutingModule        
      ],
    }).compileComponents();
```
> After import HomeComponent and other components, below error showed up. Adding al required components looks like not fancy. `Recommend to find other way`

**Comment by EdwardBaek** [comment]
### Better way instead of adding all required components
Use RouterTestingModule instead of custom router module.

```typescript
import { RouterTestingModule } from '@angular/router/testing';
...
beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [AppComponent],
      imports: [RouterTestingModule],
      schemas: [ NO_ERRORS_SCHEMA ]
    }).compileComponents();
  }));
```

> Refer [Angular-tour-of-heroes](https://github.com/rpoitras/angular-tour-of-heroes/blob/master/src/app/app.component.spec.ts).
> Refer [Angular Guid - Test](https://angular.io/guide/testing) and [Angular test code ](https://stackblitz.com/angular/jeeoonxljln?file=src%2Fmain.ts)
